### ISSUE TITLE
Please provide screenshots.

### ISSUE THREAD

**Issue by uajain** [flathub/com.toggl.TogglDesktop#2]
It would be great if the maintainer of this application can provide some screenshots in the flatpak manifest for Software clients to show-case in general.

**Comment by MartinBriza** [comment]
Hmm, seems the screenshot description in the appdata specification changed and we're still using the old spec. I was stumped why is this still an issue because we've updated the package a few times in the meantime already. I'll update the metadata in an attempt to fix this, hopefully it is the source of the issue.

**Comment by Newbytee** [comment]
Seems to have been fixed at some point.
